#!/bin/bash

if [[ $1 == "configure" ]]; then

	update-rc.d hdmimonitor defaults 2>/dev/null 1>/dev/null >/dev/null;

	if [ -f "/usr/local/etc/hdmimonitor/settings.reuse" ]; then
		mv /usr/local/etc/hdmimonitor/settings.conf /usr/local/etc/hdmimonitor/settings.new;
		mv /usr/local/etc/hdmimonitor/settings.reuse /usr/local/etc/hdmimonitor/settings.conf;
	fi

	chmod 777 /usr/local/etc/hdmimonitor/settings.conf

	/etc/init.d/hdmimonitor start 2>/dev/null 1>/dev/null >/dev/null; 

fi
